### ISSUE TITLE
[Change Request] Test workshop comments chapter 7 & 8

### ISSUE THREAD

**Issue by bartvanb** [vantage6/vantage6-workshop#146]
**Description**

- I don't know whether I would add the algorithm code to the slides. HOw about just a bit of pseudocode? 
- I also think a white background is more visible.
- Change the shell prompt in terminal to a simple one, see howto in the first instructor note of chapter6 https://workshop.vantage6.ai/instructor/chap6_setup_node.html
- With just the information from the previous slides, I think it is very hard to already answer the first challenge
- I got this warning (mine is a fresh venv): `/Users/hcadavid/temp/wshop/venv/lib/python3.12/site-packages/copier/template.py:140: OldTemplateWarning: This template was designed for Copier 8.0.0, but your version of Copier is 9.2.0. You could find some incompatibilities.`
- add maybe a quick recap of what the central/partial function is?
- Pause a bit for each question of `v6 algorithm create` (also other commands if applicable) to wait participants to finish it; otherwise they will miss what you're saying
- Go through or explain the output of each command even if it's simple and obvious.
- People may try to do the `avg algorithm update` when shown on the slide. I'm getting this warning `[warn ] - Update failed: Updating is only supported in git-tracked subprojects`.
- I'm not sure at this point participants know what the alg. store JSON file is for.
- This is a little up for debate but if we use jupyter for file inspection and everything it will be nice and cohesive, and then we are sure that the researchers have this tool
- Set a time limit for each challenge, e.g. this challenge you will have 5 mins to finish.
- Do people already know how to do the math for the average algorithm challenge? So the idea of the central/partial part, is that clear enough?
- I think the `v6-test script` concept should be introduced in more depth early in the presentation. I think it is extremely important for developers to understand how it works and how you can test a federated algorithm with it. Without a proper introduction it won't be easy for the participants to understand and hence to modify the `test` boilerplate created by the `v6 algorithm` command. 

- [Setup] ask users (day 2) to create a docker account beforehand.

- Error:
```bash
(base) ➜  v6 dev start-demo-network
....
[info ] - Please check the node logs to see if the node successfully connects to the server.
[info ] - To see the logs, run: v6 node attach --name bartje3_node_1
[info ] - Linking local algorithm store to server...
Failed to authenticate: Failed to login
Traceback (most recent call last):
  File "/home/dsmits/miniconda3/bin/v6", line 33, in <module>
    sys.exit(load_entry_point('vantage6', 'console_scripts', 'v6')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dsmits/miniconda3/lib/python3.12/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dsmits/miniconda3/lib/python3.12/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/dsmits/miniconda3/lib/python3.12/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dsmits/miniconda3/lib/python3.12/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dsmits/miniconda3/lib/python3.12/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dsmits/miniconda3/lib/python3.12/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dsmits/miniconda3/lib/python3.12/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dsmits/projects/CARRIER/vantage6/vantage6/vantage6/cli/dev/start.py", line 96, in start_demo_network
    client.authenticate(USERNAME, PASSWORD)
  File "/home/dsmits/projects/CARRIER/vantage6/vantage6-client/vantage6/client/__init__.py", line 142, in authenticate
    auth = super(UserClient, self).authenticate(auth_json, path="token/user")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dsmits/projects/CARRIER/vantage6/vantage6-common/vantage6/common/client/client_base.py", line 409, in authenticate
    raise AuthenticationException("Failed to authenticate")
vantage6.common.exceptions.AuthenticationException: Failed to authenticate
```
I suspect it went wrong because there was already vantage stuff running

**Comment by bartvanb** [comment]
I removed the things from this issue that had to do with the way of teaching since these details will have to be redone for next workshop
